// <auto-generated />
using System;
using CrawlerApp.Client.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrawlerApp.Client.Migrations
{
    [DbContext(typeof(CrawlerContext))]
    partial class CrawlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CrawlerApp.Client.Models.AssociatedLink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int?>("LinkID");

                    b.HasKey("ID");

                    b.HasIndex("LinkID");

                    b.ToTable("AssociatedLink");
                });

            modelBuilder.Entity("CrawlerApp.Client.Models.Link", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<bool>("IsCrawled");

                    b.Property<string>("Response");

                    b.HasKey("ID");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("CrawlerApp.Client.Models.AssociatedLink", b =>
                {
                    b.HasOne("CrawlerApp.Client.Models.Link")
                        .WithMany("AssociatedLinks")
                        .HasForeignKey("LinkID");
                });
#pragma warning restore 612, 618
        }
    }
}
